version: '3'

services:
  ms-users-server:
    image: nginx:1.23.3-alpine
    container_name: ms-users-server
    volumes:
      - ${MS_USERS_BASEPATH:-.}/docker/nginx/conf.d/:/etc/nginx/conf.d/
      - ${MS_USERS_BASEPATH:-.}/:/var/www/html/
    ports:
      - ${MS_USERS_PORT:-80:80}
    networks:
      - ms-users-network
      - app-network
    command: nginx -g "daemon off;"

  ms-users-php:
    build: ${MS_USERS_BASEPATH:-.}/docker/php
    container_name: ms-users-php
    image: ms-users-php
    volumes:
      - ${MS_USERS_BASEPATH:-.}/:/var/www/html/
    networks:
      - ms-users-network
      - app-network

  ms-users-db:
    build: ${MS_USERS_BASEPATH:-.}/docker/pgsql
    container_name: ms-users-db
    image: ms-users-db
    environment:
      POSTGRES_PASSWORD: ms-users
      POSTGRES_DB: ms-users
      POSTGRES_USER: ms-users
    ports:
      - ${MS_USERS_DB_PORT:-5432:5432}
    volumes:
      - ms-users-db:/var/lib/postgresql/data
    networks:
      - ms-users-network

  ms-users-redis:
    image: redis:7-alpine
    container_name: ms-users-redis
    volumes:
      - ms-users-redis:/data
    networks:
      - ms-users-network

networks:
  app-network:
    name: app-network
    driver: bridge
  ms-users-network:
    name: ms-users-network
    driver: bridge

volumes:
  ms-users-db:
    name: ms-users-db
    driver: local
  ms-users-redis:
    name: ms-users-redis
    driver: local
