version: "3"

services:
  ms-payments-server:
    image: nginx:1.23.3-alpine
    container_name: ms-payments-server
    volumes:
      - ${MS_PAYMENTS_BASEPATH:-.}/docker/nginx/conf.d/:/etc/nginx/conf.d/
      - ${MS_PAYMENTS_BASEPATH:-.}/:/var/www/html/
    ports:
      - ${SERVER_PORT:-}:80
    networks:
      - app-network
      - ms-payments-network
    command: nginx -g "daemon off;"

  ms-payments-php:
    build: ${MS_PAYMENTS_BASEPATH:-.}/docker/php
    container_name: ms-payments-php
    image: ms-payments-php
    volumes:
      - ${MS_PAYMENTS_BASEPATH:-.}/:/var/www/html/
    networks:
      - app-network
      - ms-payments-network

  ms-payments-db:
    build: ${MS_PAYMENTS_BASEPATH:-.}/docker/pgsql
    container_name: ms-payments-db
    image: ms-payments-db
    environment:
      POSTGRES_PASSWORD: ms-payments
      POSTGRES_DB: ms-payments
      POSTGRES_USER: ms-payments
    ports:
      - ${MS_PAYMENTS_DB_PORT:-5432:5432}
    volumes:
      - ms-payments-db:/var/lib/postgresql/data
    networks:
      - ms-payments-network

networks:
  app-network:
    name: app-network
    driver: bridge
  ms-payments-network:
    name: ms-payments-network
    driver: bridge

volumes:
  ms-payments-db:
    name: ms-payments-db
    driver: local
